### ISSUE TITLE
Rendering outside of Livebook?

### ISSUE THREAD

**Issue by brainlid** [livebook-dev/vega_lite#11]
Can vega_lite be used to render graphics/charts _outside_ of Livebook?

Like can I add this to a regular Phoenix application and generate/render a chart?

Looking at the docs I didn't see a way to do that.

**Comment by josevalim** [comment]
@brainlid yes but the wiring is up to your self. In this case you would export it to the json spec and pass the json spec to the VegaLite code in JS land.

**Comment by josevalim** [comment]
@brainlid if you figure it out and you want to send a PR for the docs, it will be very appreciated :)

**Comment by jonatanklosko** [comment]
@brainlid just yesterday I put together an example of that [in this repo](https://github.com/jonatanklosko/vega_lite_lv_example), let me know if that's what you're looking for :)

**Comment by brainlid** [comment]
@jonatanklosko I think that's _exactly_ what I was looking for! :smile: Thanks! You're awesome! :100: :1st_place_medal:
