### ISSUE TITLE
VegaLite.new/0 makes x axis go to top

### ISSUE THREAD

**Issue by sleepiejohn** [livebook-dev/vega_lite#12]
From the [post on Elixirforum](https://elixirforum.com/t/vega-lite-charts-in-elixir-livebook/41809) it seems that while rendering the chart vega_lite is placing the x axis at the top instead of the bottom while using the `Vl.new/0` initializing function, this behavior is fixed by using `VegaLite.new(width: 100, height: 100)` (any size, even smaller).
Even using something like 

```
Vl.new()
|> Vl.encode_field(:x, "myaxis", axis: [orient: "bottom"])
```
does not work.

On the top without size in `new`:
![visualization](https://user-images.githubusercontent.com/5256711/130308528-633614cd-8673-4d6f-a3a8-181916f449cc.png)
With size of 10x10:
![visualization(1)](https://user-images.githubusercontent.com/5256711/130308527-e0ab9ccc-8801-45ab-bdc2-d03e6aba6aab.png)
With size of 100x100:
![visualization(2)](https://user-images.githubusercontent.com/5256711/130308526-d7a02615-4365-4040-8f7e-c04d9accd359.png)

Livebook if needed: [vegalite-issue.livemd.txt](https://github.com/livebook-dev/vega_lite/files/7024776/vegalite-issue.livemd.txt)

**Comment by jonatanklosko** [comment]
Hey @sleepiejohn!

First of all, this package only produces a Vega-Lite specification, which in this case works as expected, but the chart indeed ends up weird. For the record [here](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoCDQBecNAGYlmGgkuoAjEu27HTgAwBfBSfOOAEy29kGuOnpoTmK+-hZRIQ7W4e5ogT4Aur4gcLJQbMo0smRooAAepSAAZjRwgspoIHZJ3tmCSACecABORqC5+YXFlR2VNXUN6G6RrUrI3QDWjThsRZggsTl5BUUlmiCj++P1jabxsyDzS+jCspbeGUrd+myCpJXQOo6ghyBFynAcLkAbJ1q1vEA) is a plain Vega-Lite reproduction.

We could open an issue upstream, but when I think about it, I'm not really sure what the behaviour of two independent nominal axes should be, so I can imagine the chart gets all confused.

In the given example the axis represent quantitative values, so the encodings should specify `type: :quantitative`, which helps. If there actually were multiple nominal axes, then it's a much better idea to encode them as color/shape :)
