### ISSUE TITLE
multiple datasets

### ISSUE THREAD

**Issue by dustinfarris** [livebook-dev/vega_lite#16]
I have a use case where I need to provide multiple datasets to a Vega spec.

It would be nice to support this:
https://vega.github.io/vega-lite/docs/data.html#datasets

Basically I'm looking for an API along the lines of:

```ex
Vl.new()
|> Vl.datasets_from_values([
  main: my_main_data,
  other: my_other_data,
])
|> Vl.data_from_name(:main)
...
# Example usage (already possible)
|> Vl.transform(:lookup, :some_key, from: [data: [name: :other], key: :some_key, fields: [:some_field]])
```

**Comment by jonatanklosko** [comment]
Available in `v0.1.2` :)
