### ISSUE TITLE
Keyword atom config should honor cases since config is case-sensitive

### ISSUE THREAD

**Issue by christhekeele** [livebook-dev/vega_lite#24]
I noticed that this does not render as desired, with the `x` axis on top:

```elixir
VegaLite.new
|> VegaLite.config(axisX: [orient: "top"])
|> VegaLite.mark(:square)
|> VegaLite.encode_field(:x, "x")
|> VegaLite.encode_field(:y, "y")
|> VegaLite.data_from_values([%{x: 0, y: 0}, %{x: 1, y: 1}])
```

`VegaLite` is downcasing the `axisX` atom in the config, becoming:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "config": {"axisx": {"orient": "top"}},
  "data": {"values": [{"x": 0, "y": 0}, {"x": 1, "y": 1}]},
  "encoding": {"x": {"field": "x"}, "y": {"field": "y"}},
  "mark": "square"
}
```

Which renders as:

<img width="97" alt="Screen Shot 2021-12-29 at 9 58 53 PM" src="https://user-images.githubusercontent.com/1406220/147718155-1d4a5b30-2462-4d63-986f-2cc13e54683a.png">

Using a two-tuple list preserves the casing and works, so this is only a minor wart on the DSL:

```elixir
VegaLite.new
|> VegaLite.config([{"axisX", [orient: "top"]}])
|> VegaLite.mark(:square)
|> VegaLite.encode_field(:x, "x")
|> VegaLite.encode_field(:y, "y")
|> VegaLite.data_from_values([%{x: 0, y: 0}, %{x: 1, y: 1}])
```

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "config": {"axisX": {"orient": "top"}},
  "data": {"values": [{"x": 0, "y": 0}, {"x": 1, "y": 1}]},
  "encoding": {"x": {"field": "x"}, "y": {"field": "y"}},
  "mark": "square"
}
```

<img width="96" alt="Screen Shot 2021-12-29 at 10 01 27 PM" src="https://user-images.githubusercontent.com/1406220/147718262-e2c3238d-2eaf-43fb-9772-d230d966d1a3.png">

**Comment by jonatanklosko** [comment]
Hey @christhekeele! The keys are automatically converted from snake_case to camelCase (as noted [here](https://hexdocs.pm/vega_lite/VegaLite.html#module-options)), so if you do `axis_x: [orient: "top"]` it should work fine :)

**Comment by christhekeele** [comment]
Oh I totally missed that, thank you!

**Comment by jonatanklosko** [comment]
I added an extra admonition block right after the first examples in the docs (f25650e7d05fc91ffa3557f5cf6f63ec7eabd8d4).
