### ISSUE TITLE
How Can I Render a Chart from JSON

### ISSUE THREAD

**Issue by joeybellerose** [livebook-dev/vega_lite#34]
I'm hoping this is a simple question, but it's at least one I couldn't figure out. 

I have some Vega-Lite JSON that I'd like to use to render a chart in livebook, but I can't figure out how to get it to work.  I keep getting the VegaLite struct to render.

What am I missing here?  

Thanks in advance for your time.

![image](https://user-images.githubusercontent.com/28072958/180618752-9664deda-1a9c-4994-b4fe-b6fa69861b12.png)

**Comment by josevalim** [comment]
Do you have the kino_VegaLite dependency?

**Comment by joeybellerose** [comment]
Nope!  That was the problem.  I knew it had to be something simple.  Thanks so much for the help!
