### ISSUE TITLE
wrong local path to find npm bin

### ISSUE THREAD

**Issue by revati** [livebook-dev/vega_lite#35]
Currently needed npm pacakges are searched in wrong local directory. Missing assets prefix (it is default standard setup in phoenix).

This is crude soluton. It might break it for others:
```diff
+local_bin = npm_bin(npm_path, ["--prefix", "./assets"])
-local_bin = npm_bin(npm_path)
global_bin = npm_bin(npm_path, ["--global"])
```

Probably better solution would be to provide some configuration options.

**Comment by josevalim** [comment]
Instead of hardcoding, we should support a prefix option. A PR is welcome!

**Comment by revati** [comment]
Which options would be better

```elixir
config :vega_lite, prefix: "assets"
# or
config :vega_lite, local_npm_options: ["--prefix", "assets"]
```

First one seems cleaner, but second one provides much more versatility. Im not sure it is even needed there tho.

**Comment by josevalim** [comment]
Could we pass those as actual options to the VegaLite.Export functions? If so, I would go with `local_npm_prefix: "assets"`. :)

**Comment by revati** [comment]
Can you please look at PR. I will change config parameter name, but i probably didn't do it as you wanted.

**Comment by josevalim** [comment]
Yes, we shouldn't use config files. Instead we should pass those as options to the functions in VegaLite.Export. :) Like they will support options like `opts \\ []` and we will pass those options downstream to the node functions.
