### ISSUE TITLE
Adding non channel items results in an error

### ISSUE THREAD

**Issue by mfeckie** [livebook-dev/vega_lite#38]
If I try add `view` (https://vega.github.io/vega-lite/docs/spec.html for configuring background of the chart https://vega.github.io/vega-lite/docs/spec.html#view-background) to the spec like this

```ex
      |> VegaLite.encode(:view,
        fill: "#f3f3f3"
      )
```

it results in an error `unknown channel, expected one of :x, ...`

We are limited by this collection of known channels:

https://github.com/livebook-dev/vega_lite/blob/v0.1.6/lib/vega_lite.ex#L374-L388

The workaround I can do is

```ex
      |> VegaLite.to_spec()
      |> Map.put("view", %{fill: "#f3f3f2"})
```

Would there be place for a non-channel function for adding to the spec?

**Comment by jonatanklosko** [comment]
Hey @mfeckie! You can pass arbitrary top-level properties when creating the struct, in this case:

```elixir
VegaLite.new(view: [fill: "#f3f3f2"])
```

Is this what you are looking for?

**Comment by mfeckie** [comment]
Perfect, thanks!
