### ISSUE TITLE
code for labelAngle results in invalid json in vegalite editor

### ISSUE THREAD

**Issue by jjwAmtelco** [livebook-dev/vega_lite#39]
the following code results in a labelangle property that the editor does not recognize. and if the case is changed to 'labelAngle:' it works fine in the editor. NOTE:  The elixir code **never** changes the angle of the text; though it should since fixing the code in the editor works as expected.  'tickCount' has the same issue by the way,  

`# elixir code
 data = skill_stats
    # data |> dbg
    Vl.new(title: "Service Level By Skill", description: "")
    |> Vl.data_from_values(data)
    |> Vl.concat([
      Vl.new(width: 700, height: 200)
      |> Vl.encode_field(:x, "skill",type: :nominal,title: "",
      axis: [ labelAngle: -45]
      )
      |> Vl.encode_field(:y, "value", type: :quantitative)
      |> Vl.encode_field(:color, "series", scale: [scheme: "spectral"], legend: [orient: "left"] )
      |> Vl.encode(:tooltip, [
        [field: "series", type: :nominal, title: "category"],
        [field: "value", type: :quantitative, title: "count"]
      ])
      |> Vl.mark(:bar)
    ], :horizontal)

    |> Vl.to_spec()
    |> Jason.encode!()
`

[chart]([Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoCHABONfWhCD9EAAT0ks+2MUgIMNmczWA6jSybDgAzO4QANY0goLWAO6BwWFK2rpwaAAsAGwAvgom5pYG6LYQDk4uAEwADOFePv6JoeFRMfFNySCpemgAjJV5BRZWJXaOMM72vW5Knt6+6AFBzbOtsegJy53d6ahiYoMehSM2YxVTtbP1CyBLSS3R6yCb9yk6PajTh6bDxSBkZjganM40mNTq80aWwebQ2HXcOzQAA4AOzfY5-JBMZzKOT2CAATwgmEQEIai3hq0e7WhbzSaGq6N+1ixOLxSDIcFkviukIptI8axpry6712GSZRWspXKExcMw812sAGV1Jh2LJelkYU9iWoNVqEWK0Ll8kdmaMyqCqpdFXyQKr9XJDVTYR41QbtXSPlkDmaflLLbLJtMyTdHernV7BdT0HrI5ro4jPoz-RjpWc5RcwyqPVGddZ456jfTUCjU0NA-9AcCzNb7ODeeSHXnEwW462XaLS71JSdWbJcS5CcTSU3w53o5FY+6nW3vbsBmmLSAB0P7ByuTy7c2I8XXbrJyWPiE+38ZfWFXNd637Cj+lehR253eH8fdr1e8uqxfzo2dxOL73pUj4zkWeLAQqyZLpWJy-lmobjrmQFvgeha3pB75oGIX6weemYhra16AQmr4ge2s6kZhC7IgAnGe1gAkCJJ1n+RFKuge4QahMZuuBLjUd2Hwoqe379tig54iOJIIDmnEYTx058Qp5E0agEpiZiEnrpu3JyS2KGqbxh6GVBxrqQxQaXvpXECf0GQUfxZEOWplS4eaP4ETaNkqS5xnoYZfnJl8mkZla5yIQByFUfZjm+VhqAhGioVWRF7H2rZzlxYFCUojBHknExtb1v+xHRRqWVoc+MWVEF5m9EilmrtpUlEjJPk5VVlEVcBdWlhpeEsi1Li6duZXyZ1-nVT1sVqQNBX4eFWZXhxBmkZ0SkmetCWVPlAZwV5DbpTeL4bU+3V4ts5kZKJg2pQhK0ZbeZ1gc9CUhI1KWnEthEddtXVOVdpZiPN+1-EVLElcdJEVS9ymnQlqJNWurWjrJSETf9U0XS4QMfBWC1DWyI2cnpGNrbD2VY8FTXwZMj27jgzg0J4jlM7ILMwO9oPpvdYLQyq7Oc2zzOs2ppp3d9wYuJF40OkLYvYxACtc2pKL0V9dMywLnEqyLHOK8mYifZLEMgmxNl6wDVtCbsIQS4T6Ao8ObVjlFuui6rSs29ByPDRupNjatyo25thY++ZBNg2F0uuPpAAKgLKDQUDqqQ9gAMI6LEXU4EnKdp3A9hQNn9hmGwDDqrIZAJe50d8955OJ3AyepzQ6dZ20uf5236clzEZcV1XNdqcbtOHbLq3N63heZ9nFF5y3Bft0X-eCIPleBCPtvYQ79dS-WvQ6yA0-Lx38-d0vver6X5eb9XtdNWbrFZqVU897Pnc59ji8zyvxe3yHlvWu1Qo682asTfErt0buxPh-f+X8F7wL7oA++28jZ+0gaNBOyCi6IMvn-FBA877D0fprQ6DMbjxwzhnBeUAoA7Vuo7A+Fsm40LoQwtSvQeYri1lMSh1hqG0NzvQxh48frawTuwkRnCd5lj9KbGskNWGwKERw3KmDJIuzRlI4RP9RGj00TpQOuj1FcPEbHAR6B45IDMBEewAB5MwTA6AL1sfY7wLjtzQR4Z5CRR0E7uMcc41xucgmeNCXIyoTD958MnvaGxdjgleLcUkiJ3jzL2wsYfY+iT7FOJSWEtJISMmliyHXcBz8oaBKSQUyJYd0BM2KYUqJe9wHOygTopuQS6ljXOk0jxJSEpgJXB07B3TalDKKYMlpvtyH+KsSAAAcmwewABBQO9hlRCi6kEAOW58Q7LkThbJKi5YrPWZs7Z1JdmrNGocm5xyKm8Inosi5GyDnXK7tjPZ9yw5qxieAuJx93lXKOQ0kAvzNn-KiSMqsVSzmrVBZ88F50oUHJhcmWiCjmEdOkm7c5qyPnci2aimc6KSWYvMntdp-txmwORSSr538IUUswA875yZfEHQWfpAAsinCYcAWXnQQIKpAwr3pwp5bHN+9oBWwAlSKmcYrFWSrmji2Jrz+XivVdjVVQrv7QWSpLYFOq1XKrdAapVuVuXgyUebV+x8FWGootavVyYshtNGf7fFMC5YuptV1d1RrMlGPZCY8mga9UQpDQlO1MdrJRrgHATAfL0jBpTZgBAGa5EZBNswvhcrmzptTemt1Wac3xu9X42O8SS1ZvLZm1NVa1YFq1f4o+-LG25tjZW3NwUE3oARU67tZbe2iv7QlX04btHtWTeOitLaB3UtnfssmsDS1ponSqqdalAUvN5cm1uOgK0ntDaWEI0rFqyudVfU9mbz1StOQ9btT7H0pwfXIkIQ6WEITve+-V96L0fH6E-B1L9+Zvs-Zap4ObAPJiRBrSWeLoHQf7memDCVNW0qwZGzdwHMMYdci++m+kAAyxBBAhH4A46IFFBBUZo2wejrkcOHtvRRpjtHWPY0Y9R-gLGQN21IzLRZlGBN0dg9KbjQnp3sdrTkrjkneMQv48x3jwVr2MQg9U8mEmaNSYY7JzTmTnlVlQ102BBmePSZKCZ4TDI130rljZozXV1OCdMz2UTcd9PcYzmwBAOBbAAA9jMCagEFkLcBwtcPbUCw6xabg2cC8FsLEWaNRfS7F6dvn60pYC9FjLHnuPZZi3F79NaZVKf8wJtLFXMv8HKyV1p4HmKOqg3VmjDXWtqbK8V3LakkS-ss-O6zRWcuVf65FwblWuXOfw65ybjXSuzam2Q01FDlOVH4OmwDM3dvwaw65A9inEX2gk7t-bJ2+NUaO4R8W5masRXE-dvbj27uCAewh+qZ2Xv-p2x9g751+M-du567Tw7dMXebFd4Ht3Dv8GO8R79JrcW+rQ3V67n2kco6-cmf7Wk8NbiBzd1HePPs03mZY5TvR+AACEkAQBThF+n2IWeyKNgpgHXWJuCHp0zznbP+Ac9Z-uonibXt08Z8z8XX32dy65+ZarN7av88F0rkXYvldlPa8VWHhWBey+F2txXpuomS6dpjqzy3jdC-lzN838uFtfTGUt1aEnNcW6d6LrX+7fPiaQFEFw5G4CkHXnDJ4ghg+BHsLYCP9g8a7DEFDv9fPXOx9D+H4VSeGNZ-jznyP2H8tB5D-YMPieo-SgLwn3PyfMjPbV2lCjBfK-1-z+Xuvxe5ro-3iOjPnu29F7zx52vI+G9lib0TLRnTxuZ-L+3nvfHx9V-eot0n+nh9r7H13ifwzA+t8XyPyone4-d4bOvmnenrPb9z6f3f5+T-Tr74lztZe49L8v4-lwF+H9yN6GQ0LQnmPnIzv3Xn-zU1X3v2nTTwH0blv2P0T0gNB2gIgOwwSx9UgT9SP0-2fx-0L2QIPzdzpQ90u3AO-xXz3yILUjTz4Q-2z0T16DP1-xH2YNHl-SLVAIoPYKoKfyYJ2lL1wMYNz14KgOoNEOnRpQ43VwXzwIEIIIv14K5VfxXHgICS3yQMkMULYLyxIOwKx0QPkO0L4NYIULkVVxn2MU3yMJEPXjENQIkPsKvy2yPVgQAHEuRzAv0IVSZvDHNEogCO1ONyZPDZB-CKI-CzACdrpp8G5+F9IwiIiuooiYjgZpDztAdQivDoi7N-gci0iTxf11DktrAkjcjIiCiAjaJRsbd59VpyifDzpUiAi4iIFZ8XMGiqjKjwiKi5pD9yYABRZQAAFX0EwGZQohbhJGJCpVLDoKS2PmGLGOJEmK6mmPGLmI+BOWv2lyGNGPGLWOxg2NmKOSNk4JAP0mWMOLJTdBOMwC2N2CRDgJh1HX2JWImNuKeHuMeL6Ct3aPXBwPeJuMeQhR+LOOug3w3TlmuNWK+OsHBMeUJwGNgQABEWYmZMBYBzADAupk5lY1BsSzBcS5EFj-FSj0B0SCSsT4BiSKJ8TMSiSSTPUhDyYqTGTaSSSIUGTCTOSQF8tj52TeScT6SMThS6S5oXiOtIMEC5YhSaSRS8SxSFSJS5EkQ2ixsCVVp5SmTRTqTdT+j9COiyDmwdS+SlT9TzSACUS5Y0sc0zAoAaAmiZxst7THTCjxQ2iuD9I7TzB3S8jXS-SnSAiMgedm9X1yZfSHTgyKJAzoyPS0AQggi3861j4oz-TYygs3SYzR5ky1DXjB97R0yczsY4yMzxY10gTYFiznS3QyySzXcUNSCbDbSsygzaynh6yEzUAMjed5QfS2BlArAuooshzmTzIwypc3jqzBzhzSzZzxyylLD4iCtrBAsxzMyNy1ZVDMjfpIyFzNy5zENJzodpSb9Wytz5zLyuVezidZ8qyLy5yIVRyjyVcoSg4iyDyRyvzv0bTVp1y8Fs4HAlJDyAEYhgKITgYdy+yNCZyhy55wKOVQK14IKkTI5WS4LALEKQLvz4KUKOUAir0BSBz4Kv5UKAzZywLBByKAjU99dlFpzHyELqKkLcKb5sLIKPhaJlyATUZ6jPzSKgLWKrz2KWLfi9h3ySKsKxLWhkKhLxKyTad9zBKB4+VnAGAUA2KqL7BkBZANL158TMALAmBN45B40Tz09ZT-zKKv57A1K9LNKRLtLdL9L7BDLjLTL5BXILj38pLmK7L1LHLnzKK14dLAqDKWYjKaATKEwdpbypy9zML-L7KNK5KB4XKdA3LIqPLYrhtMD4UCyrKBLpKAqHK0r14MqIriQcqNQEoajKzDCmLbKUqgrzoXznLwqsrqrorPK9CmySdoTrKVL14WryqwqHKqqoqYrarDTXClLqz4AoAIh+AABJLy0sxa5awIDA3zCkkADOTa1a9a58w67akjXYiMhauAJao62M069a4KCys1SMw6tau666rah6+qYowq2C201646tq+66dfK8SAw23f8gG96m6s638o06wwaosqGkc4G2gv8osluWxBwAC0lGgWMzG4k4uSi8SsDC6ws5sDOAm7Gyi65fG1QQm9q8SseMmsTH0qmzOGmqIOmrGom+Cpm-4566s9mnG2mkc9mxmzi3YLIUG+1M8w3Nc4WzmvGsW+mhwCWtCspf4zU-1f8xW+C0W0s8W4myWzISSyMvWouA258o2vmk2ns9G5sJgLkGFCFJ22QcSvM3coqx252+E9AN28SkIeKlcxZAOv2kAMOjWk8RS2Q1aSO75V232qO8UGWnTOWxiuOpOhO86eOwiiy7W-SXOiiIu8xeGiNFszO928OkuqJB2m4NZd2rZcwYgCiZwYC5u6tXa4+BuhwZUDurqNu-EfuiwnyutRZHupuswFugexun4aetUmOlvcmCevuqe1u2e4e6CYO6sdO8m+uxu1e+eiFQeue3KaCu8wExq1aFe4e4+jete2ajHAaj85sG+h+7GE+ze+qOu6wNZPlBnQYgAJVboQCdrMGw0XozvtD-oAeAYHtAfMEEJZoSOXv-qAZAbAfjQFsuNQdgYwcQbmh4pKO7rQbgY-oQfAfFm3oLtwfQfgcwdLv6uNIrugdIfwcodruQfHuUG0FkCgBblbp4ecH4eUDEWQb2rWSEb4YEYHqkZEdrk9pgtXPQEkd4fkdkbUZkeOSepwdgVUeEa0ePrka0eCjaOIf0n0ekdEY0YMesbVOobqK1OgeMbsaMc0bscbKfuYcRtfpccEfcYPwAF08gVB9AoALAcBYr0B3AYAos+G1AjBQAuRRzgFNAQAotBBvA0BQAAAzSwQQURuMdMJQWwUmQp0AbwSwPSUYHJ3wEJ6AHQXYEwbEqtOMHAa6oy09HIEJzANgNgQQdUHARJkAPJ4VQpwmJQdUTAWwawEuEkMgbwAkdwTAAkdp6wIIMVWQLps0UZgp6wRESZugGZ9AKLBgDdFZtZ9AAARw0u5DoH1FIBAByECaUHCzSaQFCxZmyZsCxGFWcDIGOf4FDJCd2fGZhSmeOZAGWdWd2EhSC0CG2ZACWbSdBf2eNEmZhesBuecCmYefSG6aUHgBoDICwDQBqGqCUGQDsWsGxA4YSGUHoDQHLEZBeZAAhdhcPpTiLi-wZwJFxraByCAA))

**Comment by jonatanklosko** [comment]
We aromatically covert snake_case to camelCase, so if you do `label_angle:` it should work as expected:)

**Comment by josevalim** [comment]
@jonatanklosko we should probably add a small note to the docs, perhaps on the `@moduledoc`. WDYT?

**Comment by jonatanklosko** [comment]
@josevalim [we do](https://hexdocs.pm/vega_lite/VegaLite.html#module-options)!

**Comment by josevalim** [comment]
Perfect!

**Comment by jjwAmtelco** [comment]
new to elixir; did not realize what that meant:

Most [VegaLite](https://hexdocs.pm/vega_lite/VegaLite.html#content) functions accept an optional list of options, which are converted directly as the specification properties. To provide a more Elixir-friendly experience, the options are automatically normalized, so you can use keyword lists and **snake-case atom keys**.

do now :-)
Thank you!!
