### ISSUE TITLE
joinaggregate question

### ISSUE THREAD

**Issue by jjwAmtelco** [livebook-dev/vega_lite#41]
This elixir code I have seems ok but does not produce a chart. I have commented out the line that causes the issue; The joinaggregate line.
it is not clear to me why that line causes a blank chart.  My goal is to produce a chart like what is shown in the editor...not sure its a bug but can transform be used some other way?

`data = skill_stats

    fit_bars = Enum.count(get_skills(skill_stats)) * 22

    # will never be smaller than 200 but expand depending
    # on data [ for each skill ] and overflow to a scroll
    width = max(fit_bars - rem(fit_bars, 100), 200)

    Vl.new(title: "Service Level By Skill", description: "")
    |> Vl.data_from_values(data)
    |> Vl.concat(
      [
        Vl.new(width: width, height: 200)
        |> Vl.encode_field(:x, "skill",
          type: :nominal,
          title: "",
          axis: [label_angle: -45, label_font_size: 15])

        |> Vl.encode_field(:y, "value",
          type: :quantitative,
          aggregate: :sum,
          stack: "normalize",
          title: "percentage of calls",
          axis: [format: ".0%"],
          sort: [field: "value"]
        )
        |> Vl.encode_field(:color, "series", scale: [scheme: "spectral"], legend: [orient: "left"])
        |> Vl.encode(:order, aggregate: "sum", field: "value")
        #|> Vl.transform(joinaggregate: "value", op: :sum, groupby: "skill", as: "TotalCount")
        |> Vl.transform(calculate: "datum.value/datum.TotalCount * 100", as: "PercentOfTotal")
        |> Vl.encode(:tooltip, [
          [field: "skill", type: :nominal],
          [field: "series", type: :nominal, title: "category"],
          [field: "value", type: :quantitative, title: "count"],
          [field: "sl_percentage", type: :quantitative, title: "Service Level %"],
          [field: "abandon_percentage", type: :quantitative, title: "abandon %"],
          [field: "PercentOfTotal", title: "% of Calls per skill", type: :quantitative, format: "0.2f"]
        ])
        |> Vl.mark(:bar)
      ],
      :horizontal
    )
    |> Vl.to_spec()
    |> Jason.encode!()`

[chart in editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoJEySzlcgPo44AJyhxZ6snDQgAjJQBMAdkUgEPY0+u6C+hAABPTmkWIBEADWNIKC7gBCSBA0UAmCNvaOzkiu7r7elAAsAGwB2rpuqADMHgC+CiZmFta2Dk4ujZ4+-kpBdiEG6OEQUTGykd4ADAnJqRlZOXkFfcWl6OVVtUr1emgeYu2d5pay20UD7l5+CcGhUxHRMLHnKylp6JlsrlRvlevcSoMDjU6jpTqgxG0OiBTNceoV+hDHsMXuM3iBprMvvMPMtRqt-iBAZsQXcMXsQFCjiATo1fJVLsiujdabtBk8RoFXpMQGQ7HA1PZPrElr81gCNsDAqD0byyhVocdYY1qt4OSjurcwXS+djRkL3PqbpEIABPCCYRCyilUxUQZU7B77dVMlloXVIy1oj2Y9D8nETC1cuSRCHOJ3rIFbI2qr2HGENM56qOGlWekBNKrxM244UEqXzIuBcnuACCym0skcyiTuZDIAAHAW2em4d521nUTng-SC5VK2MI+8ZuWFqSq39a-XzE2W8PBp3KN3NRnUN5-VcDTy86Px+ap4TvuPq+g6w2VzTk3mN1vmVq0GJ+wHs0e2yfw3iyzmSISXjG8l0bOBmwfVt6WfSoe21fdOUHH8R0Lf9hVFcUHTsGcZTJBcwLvSDV3BWCu3g7de2qAdD0fX90OLSdkINa07QdBBQJAW9lxI6C13cOCELQdkvxQ+i0LHDDI0HGNXDjAi5W48D7yVVD1wo4TmlaABddoVH0KBxhwTB2HkdAAhgKA5CgNQjFAJxrOUGhZDINBQGswQ2DsdyQAAMxCQRm3QCdQiUcJ5OC0BvJCON3j8zAQH06AdEaUAuEQQYIFsKBMDsHQkv07zlHsXySiwigHXcCAGE4pQArgIL3F9fTMDYNhBFMnB7P8wLgvnNYlEwG1bHcWQ2AQFyCo5BqmpC80hrocJ3Fsh0yG8m0AmG0b0HGybZGmpFZv631FswZb0GshgFJAbbBgARwYcxTPUUzSCSo6+uq90yLcM6LpAABlexiByOBIgAGTgUhBEiABSLaRoep7nDoNQaHemavvQQMh1+ralsGXH4cRnaQEe560betwsca-qAAVcwAeT8gAVNh1DServOQRL0EWHw-IJ87BjhyI2D8yIAGEdEEKJemtashqR9wKdR16MZpnSlAADzKnWaEmUBBFMRqa1ci7+DHcLTcEAAxORMEBmgAC9GnOfTjuqpXbsJ9xScGPaprSfTNs0ZEyAqiVqtqgIkANo3-J5uz0EoRYEc97HXwzUZvL50AvfQFrRnUKBEjG5PhDd4WAYk8GJciWzUgMZWybVl70cx-T4BoMgsD9RZFiUZA7HL9AzB8ob8tkCA-J5nrJDYKbI7FSrGmMEA2G6kLY-qrPTuRYV2c5qW2GuxLdKUUUz5wJgw8MAa0j0pEm6gBgTaq9BVEwWrKBZAhv6-2PjoU+59IgACpgKDzjsKRmHoWbAJDtrEAAB3Ggyh6BoF8IPS+vsRbuGBnYUGjhIbQ0apEdINpIiA2rK0IAA)

**Comment by josevalim** [comment]
Do you get an error? Maybe it is joinAggregate, no?

**Comment by jjwAmtelco** [comment]
No error and no overflow menu to check the Jason.  I can run the code without the line in it to ge the json if that is of any use…

**Comment by jjwAmtelco** [comment]
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoJEySzlcgPo44AJyhxZ6snDQgAjJQBMAdkUgEPY0+u6C+hAABPTmkWIBEADWNIKC7gBCSBA0UAmCNvaOzkiu7r7elAAsAGwB2rpuqADMHgC+CiZmFta2Dk4ujZ4+-kpBdiEG6OEQUTGykd4ADAnJqRlZOXkFfcWl6OVVtUr1emgeYu2d5pay20UD7l5+CcGhUxHRMLHnKylp6JlsrlRvlevcSoMDjU6jpTqgxG0OiBTNceoV+hDHsMXuM3iBprMvvMPMtRqt-iBAZsQXcMXsQFCjiATo1fJVLsiujdabtBk8RoFXpMQGQ7HA1PZPrElr81gCNsDAqD0byyhVocdYY1qt4OSjurcwXS+djRkL3PqbpEIABPCCYRCyilUxUQZU7B77dVMlloXVIy1oj2Y9D8nETC1cuSRCHOJ3rIFbI2qr2HGENM56qOGlWekBNKrxM244UEqXzIuBcnuACCym0skcyiTuZDIAAHAW2em4d521nUTng-SC5VK2MI+8ZuWFqSq39a-XzE2W8PBp3KN3NRnUN5-VcDTy86Px+ap4TvuPq+g6w2VzTk3mN1vmVq0GJ+wHs0e2yfw3iyzmSISXjG8l0bOBmwfVt6WfSoe21fdOUHH8R0Lf9hVFcUHTsGcZTJBcwLvSDV3BWCu3g7de2qAdD0fX90OLSdkINa07QdBBQJAW9lxI6C13cOCELQdkvxQ+i0LHDDI0HGNXDjAi5W48D7yVVD1wo4TmlaABddoVH0KBxhwTB2HkdAAhgKA5CgNQjFAJxrOUGhZDINBQGswQ2DsdyQAAMxCQRm3QCdQiUcJ5OC0BvJCON3j8zAQH06AdEaUAuEQQYIFsKBMDsHQkv07zlHsXySiwigHXcCAGE4pQArgIL3F9fTMDYNhBFMnB7P8wLgvnNYlEwG1bHcWQ2AQFyCo5BqmpC80hrocJ3Fsh0yG8m0AmG0b0HGybZGmpFZv631FswZb0GshgFJAbbBgARwYcxTPUUzSCSo6+uq90yLcM6LpAABlexiByOBIgAGTgUhBEiABSLaRoep7nDoNQaHemavvQQMh1+ralsGXH4cRnaQEe560betwsca-qAAVcwAeT8gAVNh1DServOQRL0EWHw-IJ87BjhyI2D8yIAGEdEEKJemtashqR9wKdR16MZpnSlAADzKnWaEmUBBFMRqa1ci7+DHcLTcEAAxORMEBmgAC9GnOfTjuqpXbsJ9xScGPaprSfTNs0ZEyAqiVqtqgIkANo3-J5uz0EoRYEc97HXwzUZvL50AvfQFrRnUKBEjG5PhDd4WAYk8GJciWzUgMZWybVl70cx-T4BoMgsD9RZFiUZA7HL9AzB8ob8tkCA-J5nqsncRmPRZ9nOYCJuoAYE2qvQVRMFqygWQIffD7XnQpbYa7MEiAAqYDB6S7WQAAdxoZR6AHxZdP+wZgbsUGjhIbQ0apEdINpIiA2rK0IAA)

this is the chart without the line, in the past  when something is just wrong with the case it has still shown up in the editor...

**Comment by jonatanklosko** [comment]
This would match the chart definition you have in the Vega Editor:

```
|> Vl.transform(
  joinaggregate: [[field: "value", op: :sum, as: "TotalCount"]],
  groupby: ["skill"]
)
```

**Comment by jjwAmtelco** [comment]
Tried joinAggregate no joy

**Comment by jjwAmtelco** [comment]
That worked!!!!
Thank You

**Comment by jjwAmtelco** [comment]
I did not notice that the joinagreggate was a list in the json
Thanks
