### ISSUE TITLE
is there recommended way to update a chart when the data changes

### ISSUE THREAD

**Issue by jwaldner** [livebook-dev/vega_lite#42]
the charts i have all use the same component; and I want to update a given chart when the parameters change on the address bar.   I have it working so that the data is updated when the parameters change; I have fields and other widgets updating on the page but am unsure how to update a chart when the data changes.

Not so much expecting a detailed answer or tutorial, just maybe a nudge in the right direction...
this is my existing component [just for reference]

`attr(:id, :string, required: true)
  attr(:spec, :string, required: true)
  attr(:width, :string, required: false, default: "100")
  attr(:height, :string, required: false, default: "100")

  def chart(assigns) do
    ~H"""
    <div id={@id} phx-hook="Vega" data-chart={@spec} >
    <div class={
        "h-[#{@height}] w-[#{@width}] m-4 rounded-lg border-4 border-dashed border-gray-100"
      }>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="mx-auto mt-8 mb-8 h-12 w-12 text-gray-100"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="1.5"
          stroke="currentColor"
          class="w-6 h-6"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 013 19.875v-6.75zM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V8.625zM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V4.125z"
          />
        </svg>
      </div>
    </div>
    """
  end`

**Comment by josevalim** [comment]
Not much to do on the LiveView side. You have to push the data and write JS to update it. Btw, try the ElixirForum as well, maybe people have already done this. It is the best place for questions. :)

**Comment by jonatanklosko** [comment]
@jwaldner if you render the chart on `mount()` based on `data-chart`, then you can also do it on `updated()` with the new value of `data-chart`. An alternative way would be a LiveComponent and sending the spec via `push_event` only when it changes, this way we wouldn't put it in `data-` attribute that requires escaping.
