### ISSUE TITLE
Same code but different rendered picture with vega lite

### ISSUE THREAD

**Issue by ray-sh** [livebook-dev/vega_lite#46]
Vl.new(width: 400, height: 80)
|> Vl.data_from_url("https://vega.github.io/editor/data/penguins.json")
|> Vl.transform(density: "Body Mass (g)", groupby: ["Species"], extent: [2500, 6500])
|> Vl.mark(:area)
|> Vl.encode_field(:x, "value", type: :quantitative, title: "Body mass (g)")
|> Vl.encode_field(:y, "density", type: :quantitative, stack: true)
|> Vl.encode_field(:color, "Species", type: :nominal)

![visualization(2)](https://github.com/livebook-dev/vega_lite/assets/1198691/01e79fb7-eefb-447a-9f36-48b783c88372)

https://vega.github.io/vega-lite/docs/density.html

<img width="1557" alt="Screenshot 2023-05-28 at 18 15 43" src="https://github.com/livebook-dev/vega_lite/assets/1198691/813f7bb3-60a0-4377-b053-87ceb696e119">

**Comment by ray-sh** [comment]
OS: Mac 13.3.1 (22E261) Firefox: 109.0.1 (64-bit)

**Comment by jonatanklosko** [comment]
Fixed in `kino_vega_lite` v0.1.9 :)
