### ISSUE TITLE
What is the method to remove the actions dropdown using this binding.

### ISSUE THREAD

**Issue by severian1778** [livebook-dev/vega_lite#73]
Removing the 3 dot actions menu is a giga-irritating odyssey.   Please advise.
![image](https://github.com/livebook-dev/vega_lite/assets/32786588/a43e13a2-7758-4254-86ab-c8b55cab06f9)

**Comment by josevalim** [comment]
This library only builds the spec. How it is rendered is completely up to how you load the spec in JavaScript. Here is an example: https://stackoverflow.com/questions/63715640/how-to-hide-the-three-dot-dropdown-menu-on-a-vega-chart

**Comment by severian1778** [comment]
Cheers,   That helped, thank you!
