### ISSUE TITLE
Vega.Export.save!() function generates invalid images for PNG and SVG

### ISSUE THREAD

**Issue by zgcarvalho** [livebook-dev/vega_lite#76]
Hello,
I have encountered an issue when using the `Vega.Export.save!()` functions in Elixir Vega Lite. When generating images, both PNG and SVG types are coming out as invalid while the PDF type works as expected.
For reference, I have installed all the required npm packages globally:
```
$ npm install -g vega vega-lite canvas
```
When attempting to generate an SVG image with `Vega.Export.to_svg()`, the output starts with a deprecation warning:
```
(node:13698) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node21 --trace-deprecation ...` to show where the warning was created)
```
Once these first two lines (containing the deprecation warning) are manually removed from the SVG file, it works as intended.
Any assistance or guidance on how to resolve this issue would be much appreciated. Thank you in advance for your time and help.

**Comment by josevalim** [comment]
Should we set this option to false instead?

https://github.com/livebook-dev/vega_lite/blob/a89b17ceb2ff80369c502814c41281acc336af7a/lib/vega_lite/export.ex#L228

**Comment by jonatanklosko** [comment]
@josevalim ah, correct! The idea was to capture the error too, but that doesn't work with warnings.
